import React, { useState } from 'react';
import { ExamConfig, Question } from './types';
import SetupForm from './components/SetupForm';
import QuestionCard from './components/QuestionCard';
import { generateExamQuestions } from './services/geminiService';
import { BrainCircuit, BookOpen, Download, ArrowLeft, Eye, EyeOff, FileText, Share2, Copy, Check } from 'lucide-react';

const App: React.FC = () => {
  const [questions, setQuestions] = useState<Question[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [config, setConfig] = useState<ExamConfig | null>(null);
  const [showAnswers, setShowAnswers] = useState(false);
  
  // Google Form Modal State
  const [showFormModal, setShowFormModal] = useState(false);
  const [copiedScript, setCopiedScript] = useState(false);

  const handleGenerate = async (newConfig: ExamConfig) => {
    setIsGenerating(true);
    setConfig(newConfig);
    try {
      const generatedQuestions = await generateExamQuestions(newConfig);
      setQuestions(generatedQuestions);
    } catch (error) {
      alert("Terjadi kesalahan saat membuat soal. Pastikan API Key valid dan coba lagi.");
      console.error(error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleReset = () => {
    setQuestions([]);
    setConfig(null);
    setShowAnswers(false);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleExportText = () => {
    if (!questions.length) return;

    let content = `MATA PELAJARAN: ${config?.subject || 'Ujian'}\n`;
    content += `JENJANG: ${config?.gradeLevel}\n`;
    content += `KESULITAN: ${config?.difficulty}\n\n`;
    content += `--- SOAL ---\n\n`;

    questions.forEach((q, i) => {
      content += `${i + 1}. ${q.question_text}\n`;
      if (q.type === 'mcq' && q.options) {
        q.options.forEach((opt, idx) => {
          content += `   ${String.fromCharCode(65 + idx)}. ${opt}\n`;
        });
      }
      content += `\n`;
    });

    content += `\n--- KUNCI JAWABAN ---\n\n`;
    questions.forEach((q, i) => {
      content += `${i + 1}. ${q.correct_answer}`;
      if (q.explanation) {
        content += `\n   Pembahasan: ${q.explanation}\n`;
      }
      content += `\n`;
    });

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${config?.subject?.replace(/\s+/g, '_') || 'soal'}_export.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const updateQuestion = (updated: Question) => {
    setQuestions(prev => prev.map(q => q.id === updated.id ? updated : q));
  };

  const generateAppsScript = () => {
    if (!questions.length) return '';

    const script = `
function createQuiz() {
  var form = FormApp.create('${config?.subject || "Ujian Sekolah"} - ${config?.gradeLevel || ""}');
  form.setIsQuiz(true);
  form.setDescription('Soal tingkat kesulitan: ${config?.difficulty || "Medium"}. Generated by BUAT SOAL.');
  
  // Collect Email
  form.setCollectEmail(true);

  // Questions
  ${questions.map((q, i) => {
    let qScript = `
  // Soal ${i + 1}
  var item${i} = form.add${q.type === 'mcq' ? 'MultipleChoiceItem' : 'ParagraphTextItem'}();
  item${i}.setTitle('${q.question_text.replace(/'/g, "\\'").replace(/\n/g, "\\n")}');
  item${i}.setPoints(10);
    `;

    if (q.type === 'mcq' && q.options) {
      // MCQ Logic
      const correctChar = q.correct_answer.trim().charAt(0).toUpperCase();
      const correctIdx = correctChar.charCodeAt(0) - 65; // A=0, B=1...
      
      const choices = q.options.map((opt, idx) => {
         const isCorrect = idx === correctIdx || opt.startsWith(q.correct_answer);
         return `item${i}.createChoice('${opt.replace(/'/g, "\\'")}', ${isCorrect})`;
      }).join(',\n    ');
      
      qScript += `
  item${i}.setChoices([
    ${choices}
  ]);
      `;

      if (q.explanation) {
         qScript += `
  var feedback${i} = FormApp.createFeedback().setText('${q.explanation.replace(/'/g, "\\'").replace(/\n/g, "\\n")}').build();
  item${i}.setFeedbackForCorrect(feedback${i});
  item${i}.setFeedbackForIncorrect(feedback${i});
         `;
      }
    } else {
      // Essay Logic
      if (q.explanation) {
        // ParagraphTextItem uses setGeneralFeedback
         qScript += `
  var feedback${i} = FormApp.createFeedback().setText('${q.explanation.replace(/'/g, "\\'").replace(/\n/g, "\\n")}').build();
  item${i}.setGeneralFeedback(feedback${i});
         `;
      }
    }

    return qScript;
  }).join('\n')}

  Logger.log('Form Created URL: ' + form.getEditUrl());
  Logger.log('Form Published URL: ' + form.getPublishedUrl());
}
    `;
    return script.trim();
  };

  const handleCopyScript = () => {
    const script = generateAppsScript();
    navigator.clipboard.writeText(script);
    setCopiedScript(true);
    setTimeout(() => setCopiedScript(false), 2000);
  };

  return (
    <div className="min-h-screen pb-20 bg-slate-50 font-poppins">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-40">
        <div className="max-w-5xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2 text-indigo-700">
            <div className="bg-indigo-100 p-2 rounded-lg">
              <BrainCircuit size={24} />
            </div>
            <h1 className="text-xl font-bold tracking-tight">BUAT SOAL</h1>
          </div>
          <div className="text-sm text-slate-500 hidden sm:block">
             Generator Soal SD-SMP-SMA Otomatis
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 py-8">
        {questions.length === 0 ? (
          <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
            {isGenerating ? (
               <div className="flex flex-col items-center justify-center py-20 text-center">
                 <div className="relative w-24 h-24 mb-8">
                   <div className="absolute inset-0 border-4 border-slate-100 rounded-full"></div>
                   <div className="absolute inset-0 border-4 border-indigo-600 rounded-full border-t-transparent animate-spin"></div>
                   <div className="absolute inset-0 flex items-center justify-center">
                     <BrainCircuit className="text-indigo-600 animate-pulse" size={32} />
                   </div>
                 </div>
                 <h2 className="text-2xl font-bold text-slate-800 mb-2">Sedang Menganalisis Materi...</h2>
                 <p className="text-slate-500 max-w-md">
                   AI sedang membaca materi Anda (dokumen/teks), memetakan Taksonomi Bloom, dan menyusun {config?.count} soal {config?.difficulty} yang relevan.
                 </p>
               </div>
            ) : (
              <SetupForm onGenerate={handleGenerate} isLoading={isGenerating} />
            )}
          </div>
        ) : (
          <div className="animate-in fade-in duration-500">
            {/* Results Header */}
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-4 print:hidden">
              <button 
                onClick={handleReset}
                className="flex items-center gap-2 text-slate-600 hover:text-slate-900 transition-colors font-medium"
              >
                <ArrowLeft size={20} /> Kembali ke Menu
              </button>
              
              <div className="flex flex-wrap gap-3">
                <button
                  onClick={() => setShowAnswers(!showAnswers)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-colors border ${
                    showAnswers 
                      ? 'bg-blue-50 border-blue-200 text-blue-700' 
                      : 'bg-white border-slate-200 text-slate-700 hover:bg-slate-50'
                  }`}
                >
                  {showAnswers ? <EyeOff size={18}/> : <Eye size={18}/>}
                  {showAnswers ? 'Sembunyikan' : 'Lihat Kunci'}
                </button>
                <button
                  onClick={handleExportText}
                  className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 text-slate-700 rounded-lg hover:bg-slate-50 transition-colors font-medium shadow-sm"
                >
                  <FileText size={18} /> Export Txt
                </button>
                <button
                  onClick={() => setShowFormModal(true)}
                  className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors font-medium shadow-sm"
                >
                  <Share2 size={18} /> Google Forms
                </button>
                <button
                  onClick={handlePrint}
                  className="flex items-center gap-2 px-4 py-2 bg-blue-800 text-white rounded-lg hover:bg-blue-900 transition-colors font-medium shadow-sm"
                >
                  <Download size={18} /> Cetak / PDF
                </button>
              </div>
            </div>

            {/* Exam Paper View */}
            <div className="bg-white rounded-none sm:rounded-2xl shadow-none sm:shadow-xl overflow-hidden print:shadow-none print:w-full">
              {/* Exam Header - BLUE Background as requested */}
              <div className="bg-blue-600 p-8 print:bg-white print:text-black print:border-b-2 print:border-black">
                <div className="flex justify-between items-start">
                  <div>
                    <h2 className="text-3xl font-bold mb-2 text-white print:text-black">{config?.subject || 'Ujian Sekolah'}</h2>
                    <div className="flex flex-wrap gap-4 text-blue-100 print:text-slate-600 text-sm font-medium">
                      <span className="flex items-center gap-1"><BookOpen size={16}/> {config?.gradeLevel}</span>
                      <span>•</span>
                      <span>{questions.length} Soal</span>
                      <span>•</span>
                      <span>{config?.difficulty}</span>
                    </div>
                  </div>
                  <div className="text-right hidden sm:block">
                     <div className="text-2xl font-bold opacity-20 text-white print:opacity-100 print:text-black">BUAT SOAL</div>
                  </div>
                </div>
              </div>

              {/* Questions List */}
              <div className="p-4 sm:p-8 bg-white print:bg-white">
                {questions.map((q, idx) => (
                  <QuestionCard 
                    key={q.id} 
                    index={idx} 
                    question={q} 
                    showAnswer={showAnswers} 
                    onUpdateQuestion={updateQuestion}
                  />
                ))}
              </div>

              {/* Footer */}
              <div className="bg-slate-50 p-6 text-center text-slate-500 text-sm print:hidden">
                Dibuat otomatis oleh BUAT SOAL dengan teknologi Gemini
              </div>
            </div>
          </div>
        )}

        {/* Google Forms Modal */}
        {showFormModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
            <div className="bg-white rounded-xl shadow-2xl max-w-2xl w-full flex flex-col max-h-[90vh]">
              <div className="p-6 border-b border-slate-200 flex justify-between items-center">
                <div className="flex items-center gap-3">
                  <div className="bg-green-100 p-2 rounded-lg text-green-700">
                    <Share2 size={24} />
                  </div>
                  <h3 className="text-xl font-bold text-slate-800">Export ke Google Forms</h3>
                </div>
                <button onClick={() => setShowFormModal(false)} className="text-slate-400 hover:text-slate-600">
                  <span className="text-2xl">&times;</span>
                </button>
              </div>
              <div className="p-6 overflow-y-auto flex-1">
                <p className="text-slate-600 mb-4 text-sm">
                  Karena keterbatasan akses langsung, kami membuatkan <strong>Google Apps Script</strong> otomatis untuk Anda.
                  Salin kode di bawah ini, lalu ikuti langkah mudah berikut:
                </p>
                <ol className="list-decimal list-inside text-sm text-slate-700 space-y-2 mb-4 bg-slate-50 p-4 rounded-lg border border-slate-200">
                  <li>Buka <a href="https://script.google.com/home/start" target="_blank" className="text-blue-600 underline hover:text-blue-800">script.google.com</a> dan klik <strong>+ New Project</strong>.</li>
                  <li>Hapus semua kode yang ada, lalu <strong>Paste</strong> kode di bawah ini.</li>
                  <li>Klik tombol <strong>Run</strong> (ikon Play &#9658;).</li>
                  <li>Berikan izin akses (Review Permissions -> Allow) jika diminta.</li>
                  <li>Link Google Form Anda akan muncul di bagian bawah log (Execution Log).</li>
                </ol>
                <div className="relative">
                  {/* Code block with Dark Blue background */}
                  <pre className="bg-indigo-950 text-white p-4 rounded-lg text-xs overflow-x-auto h-64 font-mono border border-indigo-900">
                    {generateAppsScript()}
                  </pre>
                  <button 
                    onClick={handleCopyScript}
                    className="absolute top-2 right-2 bg-white/10 hover:bg-white/20 text-white p-2 rounded-md transition-colors"
                    title="Copy Code"
                  >
                    {copiedScript ? <Check size={16} /> : <Copy size={16} />}
                  </button>
                </div>
              </div>
              <div className="p-6 border-t border-slate-200 flex justify-end">
                <button 
                  onClick={() => setShowFormModal(false)}
                  className="px-6 py-2 bg-slate-100 text-slate-700 rounded-lg hover:bg-slate-200 font-medium"
                >
                  Tutup
                </button>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default App;